apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-lqyyrota
  janus-idp.io/tekton: go-lqyyrota
  backstage.io/kubernetes-id: go-lqyyrota
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-lqyyrota
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
